### ISSUE TITLE
Import String format of AzeritePowerWeights has been updated

### ISSUE THREAD

**Issue by binul** [herotc/bfa.herodamage.com#10]
Import String format of AzeritePowerWeights has been updated to support the essences in 8.2.

The current import string for AzeritePowerWeights on the HD website doesn't work at all.
So, it needs small fix:
  1. the format version is changed to **2**.
  2. need to **add a colon at the end of the azerite powers**.

here's an example
( AzeritePowerWeights:2:"Fury":1:72: 575=10, 176=8.09, 82=7.88, 522=7.82, 526=7.74, 193=7.21, 196=6.55, 192=6.36, 488=6.19, 494=6.19, 157=6.00, 438=5.77, 30=5.69, 485=5.51, 562=5.47, 482=5.20, 501=5.06, 479=5.02, 119=5.01, 486=4.94, 492=4.94, 480=4.86, 521=4.83, 478=4.82, 194=4.72, 505=4.58, 229=4.46, 451=4.24, 437=4.22, 481=4.06, 498=3.95, 523=3.91, 483=3.84, 504=3.81, 195=3.55, 561=3.41, 495=3.31, 489=3.31, 576=3.12, 560=3.11, 31=2.92, 156=2.85, 22=2.69, 459=2.60, 20=2.55, 500=2.49, 493=2.40, 487=2.40, 21=2.34, 499=2.20, 462=1.73, 18=1.64, 496=1.43, 490=1.43, 491=1.38, 497=1.38, 541=1.35, 461=1.07, 174=-0.15: )

full format seems:
`( AzeritePowerWeights:2:"Title":CLASSID:SPECID: POWERID1=SCORE, POWERID2=SCORE, ..., POWERIDN=SCORE: ESSENCEID1=MAJOR/MINOR, ESSENCEID2=MAJOR/MINOR, ..., ESSENCEIDN=MAJOR/MINOR )`

full format sample:
`( AzeritePowerWeights:2:"Warrior - Fury":1:72: 100=0.11, 103=0.12, 104=0.11, 105=0.03, 119=9.02, 156=2.95, 157=6.06, 15=0.04, 176=6.11, 18=1.86, 192=5.58, 193=6.1, 194=5.53, 195=4.16, 196=5.53, 20=1.97, 21=2.14, 229=5.08, 22=2.87, 30=4.67, 31=2.92, 38=1.83, 42=0.02, 437=7.13, 438=7.06, 43=0.05, 44=0.03, 451=4.88, 459=2.24, 461=1.37, 462=1.78, 476=0.1, 478=5.05, 479=5.37, 480=4.18, 481=4.61, 482=5.28, 483=4.74, 485=5.58, 492=3.8, 493=2.71, 494=6.34, 495=3.97, 496=1.29, 497=1.24, 498=4.03, 499=2.46, 500=2.81, 501=5.04, 502=0.01, 504=4.77, 505=4.93, 521=4.25, 522=6.15, 523=4.33, 526=6.2, 541=1.61, 554=0.04, 560=2.32, 561=4.13, 562=6.54, 568=0.08, 569=5.44, 575=10, 576=3.33, 577=2.27, 82=6.22, 83=0.14, 84=0.17, 86=0.02, 87=0.03, 89=0.01, 98=0.08, 99=0.12: 27=6.24/2.86, 28=3.07/1.62, 15=3.16/0.03, 32=1.91/1.86, 5=10/3.2, 14=9.94/3.81, 23=3.46/1.05, 22=2.74/0.92, 6=6.17/3.3, 12=7.69/3.78, 4=0.82/1.23 )`

**Comment by Mystler** [comment]
Thanks for the detailed report! This should be fixed in the next data update.
