### ISSUE TITLE
Link to wrong commit

### ISSUE THREAD

**Issue by jec324** [herotc/bfa.herodamage.com#3]
https://www.herodamage.com/rogue/azeritelevels/dungeon-pr-outlaw

links to WoW-Build: 8.0.1#d36ed40c9a

Which is: https://github.com/simulationcraft/simc/commit/d36ed40c9a

Which is for warlock T22 profiles.

**Comment by Mystler** [comment]
This is correct. It links to the last commit for the SimC build that was used for the simulation on that site. You should not expect to see something related to the class there.
However, the URL should be changed to show the commit history instead of the last commit.
