### ISSUE TITLE
Incorrect azeritePowerID for Havoc DH and Fury Warrior

### ISSUE THREAD

**Issue by binul** [herotc/bfa.herodamage.com#9]
The azeritePowerID of  _"**Chaotic Transformation**"_ for _Havoc DH_ is **220** (HD uses **555**),
and _"**Unbridled Ferocity**"_ for _Fury Warrior_ is **119** (HD uses **544**).

AzeriteForge seems support both (220 and 555, 119 and 544. TraitData.lua)
but AzeritePowerWeights suports only 220 and 119 (so, the trait score doesn't show when import from HD).

I know that in-game API like _C_AzeriteEmpoweredItem.GetPowerInfo( powerID )_ returns same spellID.
But when parsing the item using _C_AzeriteEmpoweredItem.GetAllTierInfoByItemID( itemLink )_, it returns **220** and **119**. (capture attached, i marked with a red rounded rectangle.)

![ct](https://user-images.githubusercontent.com/2541463/62341780-7ac73500-b51f-11e9-8ab8-4c76efebcf77.png) ![uf](https://user-images.githubusercontent.com/2541463/62341785-7e5abc00-b51f-11e9-83c9-665951528b9f.png)

**Comment by Mystler** [comment]
This duplicate entry issue should be fixed in the next data update. Thanks for the report!
